//Una tortilla de patatas lleva 200 gramos de patatas por persona. 
// Por cada kilo de patatas se necesitan 5 huevos y 300 gramos de cebolla. 
// Escribe un script que dado el número de 
// comensales calcule las cantidades de ingredientes necesarias

//EJERICIO 3
// ELABORA UN PROGRAMA QUE LE SOLICITE AL USUARIO LA CANTIDAD E HORAS
//TRABAJAS  Y SU TARIFA POR HORA
// COMO RESULTADO DEBE MOSTRAR EL SALARIO TOTAL DEL TRABAJADOR


//EJERCICIO  4
// ESCRIBRE UN SCRIPT QUE PIDA AL USUARIO  EL PRECIO ORIGINAL DE UN PRODUCTO
// PORCENTAJE DE DESCUENTO 
// DEBE MOSTRAR EL MONTO A DESCONTAR
//DEBE MOSTRAR EL PRECIO TOTAL MENOS EL DESCUENTO


//EJERCICIO 5
//ESCRIBE UN SCRIPT QUE ME CALCULE EN SEGUNDOS EL TIEMPO QUE DURA
// UN PERSONA USANDO EL SISTEMA 
